name: Update WakaTime Stats

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest

    steps:
      - name: Use a secret
        run: echo "My secret value is ${{ secrets.MY_SECRET }}"

      - name: Run WakaTime Stats action
        uses: shekharh500/shekharh500@main
        secrets:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
